### ISSUE TITLE
Tighter integration with Notifications

### ISSUE THREAD

**Issue by jlsjonas** [enso-ui/toastr#1]
This is  a **feature request**.

### Prerequisites
Yes

### Description

Improve support for notifications, notably:
- [x] Use broadcasted icon if provided (default to level-based icon)
- [ ] Support clickable notification (if a _clickable_ is provided in the event, use bulma's [delete class button](https://bulma.io/documentation/elements/notification/) for closing instead.

### Actual behavior

N/A

**Comment by aocneanu** [comment]
>Support clickable notification (if a clickable is provided in the event, use bulma's delete class button for closing instead.

All notifications are clickable. In the first versions we had the delete button but I decided to drop it for a simpler design

**Comment by jlsjonas** [comment]
As far as I can see, clicking the toast (i.e. "notification" in a user's perspective) just closes. https://github.com/enso-ui/toastr/blob/019dd70476f004b8111e99e927cf40f8ecb87b89/src/bulma/Toastr.vue#L9

As a sidenote: The desktop-version of the notification also (according to [the code](https://github.com/enso-ui/ui/commit/2a9ff202fbfb21937e5f67a04faa10dafecd4fbd#diff-a38b71be2a2a86008bedb010f2effaa9R155)) just focuses the window.
![image](https://user-images.githubusercontent.com/932193/57524924-a3c59880-7329-11e9-8820-285ba3498290.png)


Expected:
- clicking the toastr notification to open a notification
- (/ui component) desktop notification click to also route to provided path
